      program trackDDMreader
      implicit none
      character*80 fname,fname2
      integer :: icount,idummy,i,kk,ifound,itot,iloc,k,l,m,j,
     1 iblind1,iblind2,isw,n,kmax,iwindmax,mm,ll,ixytest
      real :: wndspeed,x,y,A,B,Pdelt,convary(600),wndselect,xselect,
     1 yselect,modeldata(112000,606),sumref,sumwork,refarray(600),work
     2 array(600),r,crosswork,bckgrnd(600),naturewave(20400),xnr,ynr,
     3 data,rmax,Amax,Bmax,xmax,ymax
      write(*,*)
      write(*,*)
      write(*,*)
      write(*,*)'This program reads DDM files generated by tracker'
      write(*,*) 'The coordinates start at x=0 and y=0 for storm cente
     1r'
      write(*,*)'Generally, the E2E and Nature Run stuff have storm
     1center as 240 and 240'
      write(*,*) 'So be aware and be careful'
      write(*,*)'You must check ntrmain.for, here, and trackermain.for'
      write(*,*)'to be sure'
      write(*,*)
      call system('ls *.txt')
      write(*,*)'Input the DDM file to read'
      read(*,*)fname
      open (unit=10,file=fname)
      open(unit=12,file='Background.txt')
      open(unit=14,file='Workingmodels.txt')
      do l=1,600
      read(12,*)i,bckgrnd(l)
      enddo
      write(*,*)'input the windspeed to select out of the data'
      read(*,*)wndselect
      write(*,*)'input the x postion'
      read(*,*)xselect
      write(*,*)'input the y postion'
      read(*,*)yselect
      ifound=0
      itot=0
      isw=0
10    read(10,*,end=1000) i,j,k,l,m,wndspeed,x,y,A,B,Pdelt,
     1 (convary(kk),kk=1,600)
      itot=itot+1
*      iloc=10164*(i-1)+924*(j-1)+84*(k-1)+21*(l-1)+m
      iloc=10164*(i-1)+924*(j-1)+84*(k-1)+4*(l-1)+m      
      modeldata(iloc,1)=wndspeed
      modeldata(iloc,2)=x
      modeldata(iloc,3)=y
      modeldata(iloc,4)=A
      modeldata(iloc,5)=B
      modeldata(iloc,6)=Pdelt
      do kk=1,600
      modeldata(iloc,kk+6)=convary(kk)
      enddo
*      write(*,*)x,y
      if(wndspeed.eq.wndselect.and.xselect.eq.x.and.yselect.eq.y)then
      ifound=ifound+1
      write(*,*)ifound,iloc,x,y,A,B,Pdelt
*      write(*,*)wndspeed,A,B,Pdelt,(convary(kk),kk=1,600)
      goto 10
      else
      goto 10
      endif
1000  write(*,*)'End of file found'
      write(*,*)'Total number of lines read ',itot,'Should be 111804'
*Permit an exclusion zone at the beginning (in the eye) and at the end (no change in waveform)      
      write(*,*)'Enter the exclusion (start) chip, NB 3 steps/chip'
      read(*,*)iblind1
      write(*,*)'Enter the exclusion end chip, Remember 3 steps/chip'
      read(*,*)iblind2
      iblind1=iblind1*3
      iblind2=iblind2*3
50      call system('ls *.txt')
      write(*,*)'Input the name of the NatureRun waveform to process'
      read(*,*)fname2
      open(unit=16,file=fname2)
40    write(*,*)'input the x postion negative stops'
      read(*,*)x
      if(x.lt.0)goto 1010
      write(*,*)'input the y postion'
      read(*,*)y 
      write(*,*)'Note that the storm center is referenced to x=250000 an
     1d y=250000'
      write(*,*)'So this must be subtracted (correct is 240 x 240)'     
      kk=1
30    read(16,*,end=20)idummy,xnr,ynr,data
*
*  Note that the storm center is referenced to x=250000 and y=250000 so this must be subtracted
*  to find the correct match with the tracker-mode model waveform specular points
*
      if(xnr-250000.eq.x.and.ynr-250000.eq.y)then     
      naturewave(kk)=data
      write(*,*)idummy,x,y,data
      kk=kk+1
      ixytest=1
      goto 30 
      else
      goto30
      endif
20    rewind(16)
      if(ixytest.ne.1)then
      write(*,*)'No x and y match found in Nature Run'
* If no match in Nature Run file, offer and opportunity to get the correct one      
      goto 50
      endif
*      write(*,*)'Input the modeldata array row you want'
*      read(*,*)i
*  The windspeed incrementing loop
      rmax=0
      do k=1,11
      do ll=1,21
      do mm=1,4
* The location in the synthetic waveform array is calculated not input now
      N=int(y/10000)
      M=int(x/10000)
      i=1+N*84+M*924 +10164*(k-1)+(mm-1)+(ll-1)*4
*      write(*,*)'Input the modeldata array row you want to crosscorrel
*     1ate'
*      read(*,*)j      
      if(i.lt.0)goto 1010
      sumref=0
      sumwork=0
      crosswork=0
      write(*,*)'Reference data',i
      write(*,*)1, modeldata(i,1)
      write(*,*)2, modeldata(i,2)
      write(*,*)3, modeldata(i,3)
      write(*,*)4, modeldata(i,4)
      write(*,*)5, modeldata(i,5)
      write(*,*) (modeldata(i,kk),kk=7,200,10)
      Write(*,*)
      write(*,*)'Crossref. data',xnr,ynr,
     1(naturewave(int((kk-1)/3)+4),kk=1,20,1)
      write(*,*)'Background data ',(bckgrnd(kk),kk=1,200,10)      
      do l=iblind1,600-iblind2
      refarray(l)=modeldata(i,l+6)

* Spread out the 204 points from Andrew to match the 3 pere chip I use.
* Skip the first 4 dead steps of the naturerun model wavefunction 
     
      workarray(l)=naturewave(int((l-1)/3)+4)
      sumref=(refarray(l)-isw*bckgrnd(l))*(refarray(l)-isw*bckgrnd(l))
     1 +sumref
      sumwork=(workarray(l)-isw*bckgrnd(l))*(workarray(l)-
     1 isw*bckgrnd(l))+ sumwork
      crosswork=(refarray(l)-isw*bckgrnd(l))*(workarray(l)-isw*
     1bckgrnd(l))+ crosswork
      write(14,*)l,(k-1)*5+30,mm,ll,modeldata(i,l+6),workarray(l)      
      enddo
* Write a blank line on workingmodels file to separate groups for gnuplot      
 
*      write(14,*)
      if(sumref.ne.0.and.sumwork.ne.0)then
      r=crosswork*crosswork/sumref/sumwork
      write(*,*)'r= ',r,'crosswork= ',crosswork,'sumref= ',sumref, 'su
     1mwork= ',sumwork
      else
      write(*,*)'Error in sumref or sumwork'
      write(*,*)sumref,sumwork
      endif
      if(rmax.lt.r)then
      rmax=r
      kmax=k
      xmax=x
      ymax=y
      Amax=modeldata(i,4)
      Bmax=modeldata(i,5)
      iwindmax=(kmax-1)*5+30
      endif
      enddo
      enddo
* Separate groups of wind speed.      
      write(14,*)
      enddo
      write(*,*)'For these values of A, B, x, and y,',Amax,Bmax,x,y,
     1 ' the windspeed is ',iwindmax
      write(*,*)'The Correlation Coefficient is ',rmax
      goto 40
      
1010  close(10)
      close(14)
      close(6)
      close(12)
      stop
      end      
